---
version: "3.8"
services:
  movies:
    image: anuhyakoganti/moviespaytm:latest
    ports:
      - 85:80
    deploy:
      replicas: 3
  train:
    image: anuhyakoganti/trainpaytm:latest
    ports:
      - 86:80
    deploy:
      replicas: 3
  recharge:
    image: anuhykoganti/rechargepaytm:latest
    ports:
      - 87:80
    deploy:
      replicas: 3
  dth:
    image: anuhyakoganti/dthpaytm:latest
    ports:
      - 88:80
    deploy:
      replicas: 3
