---
version: "3.8"
services:
  movies:
    image: anuhyakoganti/moviespatym:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: anuhyakoganti/trainpaytm:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  recharge:
    image: anuhykganti/rechargepaytm:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  dth:
    image: anuhyakoganti/dthpaytm:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
